# this_file: mkdocs.yml
site_name: Opero
site_description: Resilient, parallel task orchestration for Python
site_author: Adam Twardoch
site_url: https://github.com/twardoch/opero
repo_url: https://github.com/twardoch/opero
repo_name: twardoch/opero
edit_uri: edit/main/src_docs/
docs_dir: src_docs
site_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_bases: true
            group_by_category: true
            docstring_style: google
            line_length: 80
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Basic Usage: guide/basic-usage.md
    - Advanced Features: guide/advanced-features.md
    - Best Practices: guide/best-practices.md
  - API Reference:
    - Overview: api/overview.md
    - Core Classes: api/core.md
    - Utilities: api/utils.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Changelog: development/changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/twardoch/dotenvy
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike

copyright: |
  &copy; 2024 Adam Twardoch. Licensed under MIT License.